### ISSUE TITLE
Better to separate internal api-host:port and external api-host:port

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/openwhisk-deploy-kube#331]
I think we should separate internal used api_host and external used api_host. Currently, we mixed them, only one api_host in the environment. We use it when internal containers want to access NGINX service, we also use it when external clients want to access NGINX service. I think it's not correct.

Although the external IP and port is accessible within K8s cluster in IKS, external IP and port is only accessible outside Kube and internal IP is only accessible inside Kube in most situations.

I met with a problem when I used K8s service in Docker desktop on my Mac. Firstly, I configured internal IP `192.168.65.3` as `api_host_name` and `31001` as `api_host_port`. After OpenWhisk was installed, I configured `wsk` property by this `wsk property set --apihost 192.168.65.3:31001`. When I tried to use the command line to list actions, I met with error `connection refused`. Finally, I had to change wsk property by `wsk property set --apihost 127.0.0.1:31001`, and it worked.

I think, we have two options to resolve this issue:
- either clearly document how to set external api_host_name and api_host_port with `wsk` command line and config internal api_host_name and port in `mycluster.yaml`
- or set external api_host_name and port in `mycluster.yaml` and use `{{ .Values.nginx.name }}.{{ .Release.Namespace }}.svc.{{ .Values.k8s.domain }}:{{ .Values.nginx.httpsPort }}` to configure the internal access api_host_name.

@dgrove-oss Let me know your thoughts.

**Comment by dgrove-oss** [comment]
I agree.  The current setup is too confusing.  I think option 1 is probable better:  rename the entry in `values.yaml` to `internalAPIHostName` and then have a good discussion in the documentation about how to set the `-apihost` for the different kinds of clusters on which we deploy,

**Comment by dgrove-oss** [comment]
One complexity is that on "real" deploys on IKS, I had stripped down the nginx configuration (assuming that internal requests would go through the IKS ingress via the external host name).  We may need to revisit that (have a full nginx conf all the time, so that internal accesses can use it). 

Another issue is that when we are running with DockerContainerFactory, the user action containers aren't using kube-dns by default, so they need to use an "internal" api_host that doesn't rely on kube-dns (so we can't use the nginx service name).

But we do need to do something to clean this up.

**Comment by dgrove-oss** [comment]
I've done a major rework of the documentation in #347.  Doesn't completely address this issue, but makes some small improvements.

**Comment by dgrove-oss** [comment]
Docs have improved; I think what we have is good enough.
