### ISSUE TITLE
Question: Will this work on OpenShift 4?

### ISSUE THREAD

**Issue by troyibm** [apache/openwhisk-deploy-kube#632]
The README mentions OpenShift 3.  Do you know if there are issues using OpenShift 4?  Our goal is to use our OpenWhisk functions with latest OpenShift.  Haven't tried this with OpenShift 3.

**Comment by dgrove-oss** [comment]
I finally had some time today to experiment with this.  I updated the docs for deploying on OpenShift 4.5 in #682 .   I still used a two command apply (`helm template ...; oc create -f ...`) because I think we need `oc` to be involved to create the Route.  However, I did not try really hard to get it to work with a single helm command.  It might be possible.
