### ISSUE TITLE
No way to override runtimes.json

### ISSUE THREAD

**Issue by travigd** [apache/openwhisk-deploy-kube#635]
I want to override the runtimes.json file (in particular, I just want to disable the stem cells since I don't run nodejs in my deployment).

Could this be a customizable value? It could try to read a value from `values.yaml` and if it's not set, use the existing `runtimes.json` file.

**Comment by upgle** [comment]
Hi @travigd, you can create new runtimes-minimal.json and override it like this:

```bash
cat > mycluster.yaml <<EOF
whisk:
  runtimes: "runtimes-minimal.json"
```

https://github.com/apache/openwhisk-deploy-kube/blob/f9179825e78879f40436dbb5386268a888a0f716/helm/openwhisk/values.yaml#L126

**Comment by travigd** [comment]
For sure, but that still requires editing a file in the chart directory, which I'd rather not do (since I'd like to have all my git history outside of the openwhisk-deploy-kube repo).

**Comment by dgrove-oss** [comment]
use `-f -f mycluster.yaml` to override helm defaults.

**Comment by dgrove-oss** [comment]
For example, see how we override runtime.json when running the TravisCI tests: https://github.com/apache/openwhisk-deploy-kube/blob/master/tools/travis/deploy-chart.sh#L197-#L224

**Comment by travigd** [comment]
Like I said above, this still requires writing a file INSIDE the chart directory, when (in my humble opinion) it shouldn't. The status quo isn't the worst thing in the world (I can just automate copying the file in) but in an ideal world, I'd just have my `mycluster.yaml` file and that's it.

**Comment by dgrove-oss** [comment]
Sorry, I'm missing why this requires something inside the chart directory.  I routinely run with a mycluster.yaml located somewhere else on my harddrive.  You just give a path to -f.

**Comment by Reylak** [comment]
Hello, I'd like to reopen this issue and to explain what I think @travigd meant.

Helm requires the files included with `Files.get` to be _under_ the chart's root directory. So even by changing the runtimes manifest pointed to in mycluster.yaml, you require to include this file **inside** the chart directory. This is a hard limit to Helm, for security reasons.

Your example for Travis works because the custom runtimes manifest is already inside the directory of the Helm chart.

I think a nice solution would be to include the JSON of the runtimes file in the custom mycluster.yaml. Otherwise, we are left with including a clone of this repository (or of the Helm chart at least) in our projects.
