### ISSUE TITLE
Kubernetes version compatibility

### ISSUE THREAD

**Issue by jnamdar** [apache/openwhisk-deploy-kube#690]
Hi, I understand from the technical requirements https://github.com/apache/openwhisk-deploy-kube/blob/master/docs/k8s-technical-requirements.md that we now need Kubernetes 1.19+ to deploy Openwhisk for Kube.

Is there any way we can deploy for an older Kubernetes build such as 1.17, maybe by checking out an older version of this repo ? I do not see releases or branches that would let me do that though.

**Comment by dgrove-oss** [comment]
#687 that was merged about a month ago switched from using the `extensions/v1beta1` version of `Ingress` to the `networking.k8s.io/v1` that was released in Kubernetes 1.19.  You could go back before this commit and it should still work.

It is worth noting that Kubernetes 1.17 is well past its end of life date of 12/2020 (https://endoflife.date/kubernetes) and 1.18 also went end of life on 5/2021.  That's why we did not preserve the ability to use the old Ingress class.
