### ISSUE TITLE
Has Helm Chart been updated? getting error that mentions Ingress "extensions/v1beta1" despite being on 1.22

### ISSUE THREAD

**Issue by paul42** [apache/openwhisk-deploy-kube#710]
To Reproduce:

1. use helm to add apache charts for openwhisk
2. attempt to install using helm and try to set ingress to `Standard` like in [doc](https://github.com/apache/openwhisk-deploy-kube#deploy-with-helm)

Expected:
- Able to get ingress resource created on kubernetes cluster

Observed:
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"`

I was able to get openwhisk to deploy from helm when using a regular nodeport, but it looks like if I want to use ingress standard, I get an error like this - I have 1.22 server and client of k8s, but when I looked at the helm chart, it points at `https://openwhisk.apache.org/charts/index.yaml` which lists 
```
 urls:
        - https://github.com/apache/openwhisk-deploy-kube/releases/download/1.0.0/openwhisk-1.0.0.tgz
```
despite being created `created: "2021-02-05T18:55:49.212794-05:00"` 
this seems like it's related to #690 , but when I search through the current github codebase I don't see any existing `extensions/v1beta1` apiVersions

is there a way with helm to clone a github repo and install from that?

**Comment by dgrove-oss** [comment]
Unfortunately, we can only update the chart repository when we have official Apache releases of the openwhisk-deploy-kube project.  We're overdue to make one (1.0.0 was almost a year ago), but its been blocked on there being a new release of the core openwhisk project for several months now.

If you clone this repo, you can then deploy the chart from your local checkout and it will have all the changes we've made to the chart since late 2020.

**Comment by paul42** [comment]
Thanks @dgrove-oss appreciate the help! are there any small things I can do to help?

**Comment by paul42** [comment]
Deploying from git worked like a charm, got ingress going perfectly, let me know if there's any small tasks that could help the project, really enjoying it so far!
